name: Environment Setup

on:
  workflow_call:

jobs:
  triage:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Set up Python 3.10
      uses: actions/setup-python@v2
      with:
         python-version: 3.10.14

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip;
        pip install -r requirements.txt
