name: FinanceTask

on:
  workflow_dispatch:
  repository_dispatch:
  schedule:
    # 周一到周五 运行
    - cron: '30 7/24 * * 1-5'

jobs:
  build:
    if: github.actor == github.repository_owner
    runs-on: ubuntu-latest
    env:
     CONF: ${{ secrets.CONF }}
     PYTHONPATH: $PYTHONPATH:`pwd`

    steps:
      - uses: actions/checkout@master
      - name: Set up Python 3.10
        uses: actions/setup-python@v2
        with:
          python-version: 3.10.14

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip;
          pip install -r requirements.txt

      - name: Run
        run: |
            python3 stock/finance_daily_task.py
        env:
          PYTHONPATH: $PYTHONPATH:`pwd`
          CONF: ${{ secrets.CONF }}


