name: FinanceTask

on:
  workflow_dispatch:
  repository_dispatch:
  schedule:
    - cron: '30 7/24 * * *'

jobs:
  call-workflow-2-in-local-repo:
    uses: ./.github/workflows/envioment_setup.yml

  build:
#    if: github.actor == github.repository_owner
    runs-on: ubuntu-latest
    env:
     CONF: ${{ secrets.CONF }}
     DBENV: ${{ secrets.DBENV }}

    steps:
      - name: Run
        env:
          CONF: ${{ secrets.CONF }}
          DBENV: ${{ secrets.DBENV }}
        run: |
          echo "run"
#            python3 stock/history_gold_price_service.py


