name: Run

on:
  workflow_dispatch:
  repository_dispatch:
  schedule:
    - cron: '0 1 * * *'

jobs:
  build:
    if: github.actor == github.repository_owner
    runs-on: ubuntu-latest  

    steps:
      - name: Set up Python 3.9
      - uses: actions/checkout@master
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt


