name: Run

on:
  workflow_dispatch:
  repository_dispatch:
  schedule:
    - cron: '0 1/24 * * *'


jobs:
  build:

    if: github.actor == github.repository_owner
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master
    - name: Run
      uses: coactions/setup-xvfb@master
      with:
        python-version: 3.8.4
        run: |
          python -m pip install --upgrade pip;          
           pip install -r requirements.txt;
          python3 Bili/bilibili.py          
          echo ${CONF}
          echo "DBENV: $DBENV"
      env: 
        CONF: ${{ secrets.CONF }}


# jobs:
#   build:
#     if: github.actor == github.repository_owner
#     runs-on: ubuntu-latest

#     steps:
#       - uses: actions/checkout@master
#       - name: Set up Python 3.10
#         uses: actions/checkout@master
#         with:
#           python-version: 3.8.4

#       - name: Install dependencies
#         run: |
#           python -m pip install --upgrade pip;
#           pip install -r requirements.txt

#       - name: Run
#         # env:
#           # CONF: ${{ secrets.CONF }}
#           # DBENV: ${{ secrets.DBENV }}
#         run: |
#              python3 Bili/bilibili.py
#              echo "CONF: $CONF"
#              echo "DBENV: $DBENV"
#     env: 
#      CONF: ${{ secrets.CONF }}
#      DBENV: ${{ secrets.DBENV }}


